import './cssHook';
import './assetsHook';

import * as React from 'react';
import * as ReactDOM from 'react-dom/server';
import * as express from 'express';
import { Provider } from 'react-redux';
import { StaticRouter } from 'react-router';

import configureStore from '../../../client/store/configureStore';
import App from '../../../client/components/App';
import Html from '../../../client/components/Html';
import config from '../../../client/config';

// Assets file generated by webpack
import assets from '../../build/assets.json';

/**
 * Render React UI from server
 */
export function renderClient(req: express.Request, res: express.Response, next: express.NextFunction) {
  try {
    const store = configureStore({});
    const context = { store };
    const data = {
      title: config.app.title,
      description: config.app.description,
      favicon: '',
      styles: [assets.client.css],
      scripts: [assets.vendor.js, assets.client.js],
      state: store.getState()
    };

    let status: number = 200;
    if (context.url) {
      status = 302;
      req.originalUrl = context.url;
    }
    if (context.status === '404') {
      status = 404;
    }

    const html = ReactDOM.renderToStaticMarkup(
      <Html {...data}>
        <Provider store={store}>
          <StaticRouter location={req.originalUrl} context={context}>
            <App />
          </StaticRouter>
        </Provider>
      </Html>
    );
    res.send(`<!doctype html>${html}`);

  } catch (err) {
    next(err);
  }
};

export default renderClient;